/*
  TopicEnum: Replace DATA_SUFFICIENCY, MATH_RELATEDf, NON_MATH_RELATED
  with DATA_SUFFICIENCY_MATH and DATA_SUFFICIENCY_NON_MATH.
  Map existing data: MATH_RELATEDf -> DATA_SUFFICIENCY_MATH,
  NON_MATH_RELATED -> DATA_SUFFICIENCY_NON_MATH,
  DATA_SUFFICIENCY -> DATA_SUFFICIENCY_MATH.
*/
-- AlterEnum
BEGIN;
CREATE TYPE "TopicEnum_new" AS ENUM (
  'READING_COMPREHENSION', 'STRENGTH', 'WEAKEN', 'FLAW', 'PARADOX', 'INFERENCE', 'ASSUMPTIONS', 'EVALUATE', 'BOLDFACE',
  'ARITHMETIC', 'COORDINATE_GEOMETRY', 'PROBABILITY', 'PERMUTATION_COMBINATION', 'ALGEBRA', 'NUMBER_PROPERTIES', 'MODS_INEQUALITIES', 'STATISTICS', 'GENERAL_WORD_PROBLEMS',
  'DATA_SUFFICIENCY_MATH', 'DATA_SUFFICIENCY_NON_MATH',
  'GRAPHICAL_INTERPRETATION', 'TABLE_ANALYSIS', 'MULTI_SOURCE_REASONING', 'TWO_PART_ANALYSTS'
);
ALTER TABLE "Question" ALTER COLUMN "questionTopic" TYPE "TopicEnum_new" USING (
  CASE "questionTopic"::text
    WHEN 'MATH_RELATEDf' THEN 'DATA_SUFFICIENCY_MATH'::"TopicEnum_new"
    WHEN 'NON_MATH_RELATED' THEN 'DATA_SUFFICIENCY_NON_MATH'::"TopicEnum_new"
    WHEN 'DATA_SUFFICIENCY' THEN 'DATA_SUFFICIENCY_MATH'::"TopicEnum_new"
    ELSE "questionTopic"::text::"TopicEnum_new"
  END
);
ALTER TYPE "TopicEnum" RENAME TO "TopicEnum_old";
ALTER TYPE "TopicEnum_new" RENAME TO "TopicEnum";
DROP TYPE "TopicEnum_old";
COMMIT;
